let mode='login'; const $=id=>document.getElementById(id); const api=async(path,opt={})=>{opt.headers={...(opt.headers||{}),'Content-Type':'application/json'};const t=localStorage.getItem('fg_token');if(t)opt.headers.Authorization='Bearer '+t;const r=await fetch(path,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||'Something went wrong');return d};
function toast(s){$('toast').textContent=s;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2500)}
function showAuth(m){mode=m; $('auth').classList.remove('hidden'); $('authTitle').textContent=m==='login'?'Welcome back':'Create your farmer account';$('authSub').textContent=m==='login'?'Sign in to your farm dashboard.':'Start your FarmGuard AI journey.';$('nameWrap').classList.toggle('hidden',m==='login');$('langWrap').classList.toggle('hidden',m==='login');$('switchBtn').textContent=m==='login'?'New here? Create an account':'Already have an account? Sign in'}
function toggleAuth(){showAuth(mode==='login'?'register':'login')} function closeAuth(){$('auth').classList.add('hidden')}
$('authForm').onsubmit=async e=>{e.preventDefault();try{let body={email:$('email').value,password:$('password').value};let d;if(mode==='register'){body.name=$('name').value;body.language=$('language').value;d=await api('/api/auth/register',{method:'POST',body:JSON.stringify(body)})}else d=await api('/api/auth/login',{method:'POST',body:JSON.stringify(body)});localStorage.setItem('fg_token',d.token);closeAuth();boot()}catch(e){toast(e.message)}};
async function boot(){if(!localStorage.getItem('fg_token'))return;$('landing').classList.add('hidden');$('app').classList.remove('hidden');try{let u=await api('/api/me');$('userName').textContent=u.name;loadDashboard()}catch(e){logout()}}
async function loadDashboard(){try{let d=await api('/api/dashboard');if(!d.farm){$('dashboard').classList.add('hidden');$('setup').classList.remove('hidden');return}$('setup').classList.add('hidden');$('dashboard').classList.remove('hidden');$('greeting').textContent='Good day, '+(await api('/api/me')).name+' 👋';$('farmMeta').textContent=`${d.farm.crop} • ${d.farm.area} acres • ${d.farm.name}`;$('todayAction').textContent=d.analysis.irrigation;$('todayWhy').textContent=`Rain probability ${d.analysis.rain_probability}%. Crop risk is ${d.analysis.risk}/100.`;$('whyText').textContent=`Humidity and forecast conditions are influencing the risk score. Confidence ${d.analysis.confidence}%.`;$('riskScore').textContent=d.analysis.risk;$('riskBar').style.width=d.analysis.risk+'%';$('riskLabel').textContent=d.analysis.risk>=70?'High risk — monitor closely':d.analysis.risk>=50?'Moderate risk — take preventive action':'Lower current risk';$('riskBadge').textContent=d.analysis.risk>=70?'HIGH RISK':d.analysis.risk>=50?'MODERATE':'LOW RISK';$('temp').textContent=(d.weather.current?.temperature_2m??'—')+'°C';$('humidity').textContent=(d.weather.current?.relative_humidity_2m??'—')+'%';$('rain').textContent=d.analysis.rain_probability+'%';$('disease').textContent=Math.round(d.analysis.probability)+'%';$('confidence').textContent='early-risk signal';$('planList').innerHTML=d.actions.map(x=>`<div class="plan-item"><div class="day">${x.day}</div><div>${x.action}</div></div>`).join('')}catch(e){toast(e.message)}}
$('farmForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/farms',{method:'POST',body:JSON.stringify({name:$('farmName').value,lat:+$('lat').value,lon:+$('lon').value,area:+$('area').value,crop:$('crop').value,variety:$('variety').value,soil:$('soil').value,irrigation:$('irrigation').value})});toast('Farm created');loadDashboard()}catch(e){toast(e.message)}};
function locate(){if(!navigator.geolocation)return toast('Location is not available');navigator.geolocation.getCurrentPosition(p=>{$('lat').value=p.coords.latitude.toFixed(6);$('lon').value=p.coords.longitude.toFixed(6);toast('Location added')},()=>toast('Please allow location access'))}
async function analyzePhoto(){let f=$('photo').files[0];if(!f)return toast('Choose a crop photo first');let fd=new FormData();fd.append('file',f);let r=await fetch('/api/crop/analyze',{method:'POST',headers:{Authorization:'Bearer '+localStorage.getItem('fg_token')},body:fd});let d=await r.json();if(!r.ok)return toast(d.detail||'Analysis failed');$('photoResult').innerHTML=`<div class="result"><b>${d.disease}</b><br>Risk: ${d.risk}/100 • Probability: ${d.probability}%<br><span class="muted">${d.note}</span></div>`;toast('Crop analysis complete')}
async function generateVideo(){try{toast('Generating your situation video…');let d=await api('/api/situation-video',{method:'POST'});$('video').src=d.url;$('videoModal').classList.remove('hidden');$('video').play().catch(()=>{})}catch(e){toast(e.message)}}function closeVideo(){$('videoModal').classList.add('hidden');$('video').pause()}
function openFarm(){toast('Farm profile is available in onboarding; edit support can be added next')}function openActivities(){toast('Activity recording API is ready; dashboard activity UI is next')}function logout(){localStorage.removeItem('fg_token');location.reload()}
if(localStorage.getItem('fg_token'))boot();
